moved from react-scripts ver 1.1.1 to 3.4.1 and the 10 or so steps necessary to get it up and running. This is needed so the production build will not throw errors. If after this install the server throws the following errors: TypeError: require(...).jsdom is not a function then reinstall the npm node-jquery and then jquery modules. You may have to do this several times. A possible cause the animate.css library which for this project should be the old v3.7